version: '3'
services:
  producer:
    build: ./src/Floatc.Producer
    depends_on:
    - broker
  consumer:
    build: ./src/Floatc.Consumer
    depends_on:
    - broker
  broker:
    image: "rabbitmq:3.7.8-management"
    ports:
    - "15672:15672"
  floatc:
    build: ./src/Floatc
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    